[package]
name = "rusty_sr"
version = "0.1.0"
authors = ["James Millard <millard.jn@gmail.com>"]

[dependencies]
rand = "0.3"
clap = "2"
image = "0.12"
bytevec = "0.2.0"
alumina = { git = "https://github.com/millardjn/alumina" , features = ["images"]}


